fix: Update README.md
oscal-compass/community pull request #7
Opened 2024-05-30 07:29 UTC by vikas-agarwal76

2024-05-30 22:03 UTC, jpower432 requested changes
A few comments about what is include on what level. I think we can leave the details on collaboration in the README and just mark that issue as closed when this is merged.

2024-05-30 22:03 UTC, jpower432 commented on CONTRIBUTING.md
> +### Proposing new features
I propose that we leave this at the project level

2024-05-30 22:03 UTC, jpower432 commented on CONTRIBUTING.md
> +### Fixing bugs
Same. We should leave this at the project level

2024-05-30 22:03 UTC, jpower432 commented on CONTRIBUTING.md
> +### Merge approval
I propose we leave all merge and release workflow guidance to the individual projects.

2024-05-30 22:03 UTC, jpower432 commented on CONTRIBUTING.md
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
What do you think about suggesting the SPDX identifier text  `# SPDX-License-Identifier: Apache-2.0` for new code?

2024-05-30 22:03 UTC, jpower432 commented on CONTRIBUTING.md
> +In addition to this repository, InstructLab has three related repositories:
```suggestion
In addition to this repository, OSCAL Compass has three main repositories:
```

2024-05-30 22:03 UTC, jpower432 commented on CONTRIBUTING.md
> +We have also adopted [Contributor Covenant Code of Conduct](CODE_OF_CONDUCT.md).
Should we move this under the Code of Conduct section?

2024-05-30 22:03 UTC, jpower432 commented on README.md
> +  <img alt="OSCAL Compass logo" src="compass-circle.png" height="150">
I suggest creating a new directory call `assets` or `artwork to store the images

2024-05-30 22:03 UTC, jpower432 commented on README.md
> +Consult [maintainers](MAINTAINERS.md) for the current list of maintainers for vairous projects in the oscal-compass community.
```suggestion
Consult [maintainers](MAINTAINERS.md) for the current list of maintainers for various projects in the oscal-compass community.
```

2024-06-03 06:22 UTC, vikas-agarwal76 commented on CONTRIBUTING.md
> +### Proposing new features
ok.

2024-06-03 06:23 UTC, vikas-agarwal76 commented on CONTRIBUTING.md
> +### Fixing bugs
ok.

2024-06-03 06:23 UTC, vikas-agarwal76 commented on CONTRIBUTING.md
> +### Merge approval
ok.

2024-06-03 06:51 UTC, vikas-agarwal76 commented on CONTRIBUTING.md
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
Apache specifies the following standard header format. So instead of IBM what should we put?

Copyright [yyyy] [name of copyright owner]

2024-06-03 06:52 UTC, vikas-agarwal76 commented on CONTRIBUTING.md
> +In addition to this repository, InstructLab has three related repositories:
done.

2024-06-03 06:54 UTC, vikas-agarwal76 commented on CONTRIBUTING.md
> +We have also adopted [Contributor Covenant Code of Conduct](CODE_OF_CONDUCT.md).
We have just put the link to code of conduct. So, i believe it should be fine.

2024-06-03 06:59 UTC, vikas-agarwal76 commented on README.md
> +  <img alt="OSCAL Compass logo" src="compass-circle.png" height="150">
done.

2024-06-03 07:00 UTC, vikas-agarwal76 commented on README.md
> +Consult [maintainers](MAINTAINERS.md) for the current list of maintainers for vairous projects in the oscal-compass community.
done.

2024-06-03 18:08 UTC, jpower432 commented on CONTRIBUTING.md
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
To follow a similar approach to other projects, perhaps `The OSCAL Compass Authors`. What do you think?

2024-06-03 18:21 UTC, vikas-agarwal76 commented on CONTRIBUTING.md
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
done.

2024-06-03 18:34 UTC, jpower432 requested changes
Looks good. A couple small changes and then I think this is good to merge.

2024-06-03 18:34 UTC, jpower432 commented on README.md
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
Update copyright for consistency

2024-06-03 18:34 UTC, jpower432 commented on README.md
> +* Drive adoption of the OSCAL standard usng Trestle, Agile Authroing, and C2P tools for end-to-end compliance automation.
```suggestion
* Drive adoption of the OSCAL standard usng Trestle, Agile Authoring, and C2P tools for end-to-end compliance automation.
```

2024-06-04 13:36 UTC, vikas-agarwal76 commented on README.md
> +# Copyright (c) 2020 IBM Corp. All rights reserved.
done

2024-06-04 13:37 UTC, vikas-agarwal76 commented on README.md
> +* Drive adoption of the OSCAL standard usng Trestle, Agile Authroing, and C2P tools for end-to-end compliance automation.
done

2024-06-04 17:18 UTC, jpower432 approved these changes
LGTM with one caveat. Should we merge this with the placeholder logo or hold until #10 is completed?

2024-06-05 06:28 UTC, merged